name: Publish package to GitHub Packages
on:
  push:
    branches:
        - main
  release:
    types: [published]
  # FIXME workflow_dispatch should not be needed
  workflow_dispatch: 

jobs:
  publish:
    # Forbid manual execution on non-main branches
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        # Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@datalayer'
      -
        run: |
            corepack enable
            yarn install
            yarn run build
      -
        if: github.event_name == 'push'
        # Bump the version
        working-directory: packages/react
        run: |
            npm version --preid dev --no-git-tag-version prerelease

            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -a -m "Bump dev version"
      -
        working-directory: packages/react
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        if: github.event_name == 'push'
        # Push version bump
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Keep only the 3 latest pre releases
      - uses: actions/delete-package-versions@v4
        with:
          package-name: '@datalayer/jupyter-react'
          package-type: 'npm'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
